name: Run ESLINT
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - name: Install modules
      run: pnpm i
    - name: Run ESLint
      run: pnpm lint